from __future__ import annotations

import math
from collections.abc import Sequence

import torch
from torch import Tensor

DIGIT_TOKENS = tuple(str(value) for value in range(10))
OPERATOR_TOKENS = ("+", "-", "*", "/", "=", "(", ")")
CONTROL_TOKENS = (
    "<pad>",
    "<do>",
    "<eos>",
    "<sep>",
    "<calc>",
    "<work>",
    "<step>",
    "<final>",
    "undefined",
    "remainder",
)
SPECIAL_FIELD_TOKENS = frozenset(
    {"<do>", "<calc>", "<work>", "<step>", "<final>", "undefined", "remainder"}
)
INFO_TOKENS = frozenset(CONTROL_TOKENS)
SEPARATOR_TOKENS = frozenset({"<pad>", "<do>", "<eos>", "<sep>", "<calc>"})

# Edit these rows directly when you want to change fixed token meanings.
# Every token used by the tokenizer must appear exactly once here.
FIXED_MEANING_TOKEN_VECTORS: dict[str, tuple[float, ...]] = {
    "<pad>": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "<do>": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
    ),
    "<eos>": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
    ),
    "<sep>": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.5,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "<calc>": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.5,
        0.0,
    ),
    "<work>": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
    ),
    "<step>": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.5,
    ),
    "<final>": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        1.0,
    ),
    "undefined": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
    ),
    "remainder": (
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.5,
        0.0,
        1.0,
    ),
    "+": (
        0.0,
        0.0,
        1.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "-": (
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "*": (
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "/": (
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "=": (
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "(": (
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    ")": (
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "0": (
        0.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "1": (
        1.0 / 9.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "2": (
        2.0 / 9.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "3": (
        3.0 / 9.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "4": (
        4.0 / 9.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "5": (
        5.0 / 9.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "6": (
        6.0 / 9.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "7": (
        7.0 / 9.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "8": (
        8.0 / 9.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
    "9": (
        1.0,
        1.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ),
}

FIXED_MEANING_WIDTH = len(next(iter(FIXED_MEANING_TOKEN_VECTORS.values())))


def fixed_meaning_width() -> int:
    return FIXED_MEANING_WIDTH


def build_fixed_meaning_token_table(tokens: Sequence[str], d_model: int) -> Tensor:
    _validate_fixed_meaning_vectors(d_model)
    table = torch.zeros((len(tokens), d_model), dtype=torch.float32)
    missing_tokens = [
        token for token in tokens if token not in FIXED_MEANING_TOKEN_VECTORS
    ]
    if missing_tokens:
        raise ValueError(
            "fixed_meaning token vectors are missing definitions for: "
            + ", ".join(sorted(set(missing_tokens)))
        )
    for token_id, token in enumerate(tokens):
        table[token_id] = torch.tensor(
            FIXED_MEANING_TOKEN_VECTORS[token], dtype=torch.float32
        )
    return table


def build_fixed_meaning_position_table(sequence_length: int, d_model: int) -> Tensor:
    table = torch.zeros((sequence_length, d_model), dtype=torch.float32)
    if d_model == 0 or sequence_length == 0:
        return table
    positions = torch.arange(sequence_length, dtype=torch.float32).unsqueeze(1)
    div_term = torch.exp(
        torch.arange(0, d_model, 2, dtype=torch.float32)
        * (-math.log(10000.0) / max(d_model, 1))
    )
    table[:, 0::2] = torch.sin(positions * div_term)
    if d_model > 1:
        table[:, 1::2] = torch.cos(positions * div_term[: table[:, 1::2].shape[1]])
    return table


def _validate_fixed_meaning_vectors(d_model: int) -> None:
    if d_model != FIXED_MEANING_WIDTH:
        raise ValueError(
            "fixed_meaning d_model must match the width of "
            f"eur_ts.trainer.fixed_meaning.FIXED_MEANING_TOKEN_VECTORS "
            f"({FIXED_MEANING_WIDTH}), got {d_model}"
        )
    invalid = [
        token
        for token, vector in FIXED_MEANING_TOKEN_VECTORS.items()
        if len(vector) != FIXED_MEANING_WIDTH
    ]
    if invalid:
        raise ValueError(
            "fixed_meaning token vectors must all share one width; invalid tokens: "
            + ", ".join(sorted(invalid))
        )


__all__ = [
    "CONTROL_TOKENS",
    "DIGIT_TOKENS",
    "FIXED_MEANING_TOKEN_VECTORS",
    "FIXED_MEANING_WIDTH",
    "INFO_TOKENS",
    "OPERATOR_TOKENS",
    "SEPARATOR_TOKENS",
    "SPECIAL_FIELD_TOKENS",
    "build_fixed_meaning_position_table",
    "build_fixed_meaning_token_table",
    "fixed_meaning_width",
]
